chore(cli): generated dotfiles CLI from Bashly

diff --git a/scripts/unix/dotfiles b/scripts/unix/dotfiles
--- a/scripts/unix/dotfiles
+++ b/scripts/unix/dotfiles
@@ -114,11 +114,6 @@ dotfiles_install_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    printf "  %s\n" "--bin PATH"
-    printf "    Binary directory to install chezmoi to if not installed\n"
-    printf "    Default: ~/.local/bin\n"
-    echo
-
     printf "  %s\n" "--one-shot"
     printf "    Attempts to install your dotfiles with chezmoi and then remove all traces of\n    chezmoi from the system. This is useful for setting up temporary\n    environments (e.g. Docker containers).\n"
     echo
@@ -335,15 +330,15 @@ dotfiles_download_command() {
 
   	log_task "Cleaning '${path}' with '${remote}' at branch '${branch}'"
   	git="git -C ${path}"
-  	if git remote | grep -q "^origin$"; then
-  		git remote set-url origin "${remote}"
+  	if ${git} remote | grep -q "^origin$"; then
+  		${git} remote set-url origin "${remote}"
   	else
-  		git remote add origin "${remote}"
+  		${git} remote add origin "${remote}"
   	fi
-  	git checkout -B "${branch}"
-  	git fetch origin "${branch}"
-  	git reset --hard FETCH_HEAD
-  	git clean -fdx
+  	${git} checkout -B "${branch}"
+  	${git} fetch origin "${branch}"
+  	${git} reset --hard FETCH_HEAD
+  	${git} clean -fdx
   	unset path remote branch git
   else
   	log_task "Cloning '${repo}' at branch '${branch}' to '${dotfiles_dir}'"
@@ -398,15 +393,11 @@ dotfiles_update_command() {
   if [[ -n "${args["--nvim"]}" ]]; then
   	log_task "Updating Neovim"
   	command_exec bob update --all
-  	log_success "Updated Neovim"
+  	log_success "Updated Neovim to the latest version"
 
   	log_task "Updating Neovim plugins"
   	command_exec nvim --headless -c "lua vim.schedule(function() require('lazy').sync(); vim.cmd('qa!') end)"
   	log_success "Updated Neovim plugins"
-
-  	log_task "Updating Mason packages"
-  	command_exec nvim --headless -c "lua vim.schedule(function() require('mason-tool-installer').check_install(true); vim.cmd('qa!') end)"
-  	log_success "Updated Mason packages"
 
   	log_task "Syncing 'lazy.lock.json' file"
   	source_path=$(chezmoi source-path)
@@ -422,15 +413,13 @@ dotfiles_update_command() {
   	command_exec cp -f "${updated_lazy_lock_path}" "${lazy_lock_path}"
   	log_success "Synced 'lazy-lock.json' file"
 
-  	if git diff --exit-code -- "${lazy_lock_path}"; then
+  	if git diff --quiet -- "${lazy_lock_path}"; then
   		log_info "No changes in 'lazy-lock.json' file. Skip committing."
   		exit 0
   	fi
-  	current_path=$(pwd)
-  	cd $(realpath "$(chezmoi source-path)/..") || error "Could not cd to dotfiles directory"
-  	command_exec git add "${lazy_lock_path}" || error "Could not add 'lazy-lock.json' file"
-  	command_exec git commit "${lazy_lock_path}" -m "chore(nvim): update lazy-lock.json"
-  	cd "${current_path}" || error "Could not cd to current directory"
+  	git="git -C $(realpath "$(chezmoi source-path)/..")"
+  	command_exec "${git}" add "${lazy_lock_path}" || error "Could not add 'lazy-lock.json' file"
+  	command_exec "${git}" commit "${lazy_lock_path}" -m "chore(nvim): update lazy-lock.json"
   	log_success "Committed 'lazy-lock.json' file"
   fi
 
@@ -667,19 +656,6 @@ dotfiles_install_parse_requirements() {
     key="$1"
     case "$key" in
 
-      --bin)
-
-        if [[ -n ${2+x} ]]; then
-
-          args['--bin']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--bin requires an argument: --bin PATH" >&2
-          exit 1
-        fi
-        ;;
-
       --one-shot)
 
         args['--one-shot']=1
@@ -708,7 +684,6 @@ dotfiles_install_parse_requirements() {
   done
 
   [[ -n ${args['sourceDir']:-} ]] || args['sourceDir']="~/.dotfiles"
-  [[ -n ${args['--bin']:-} ]] || args['--bin']="~/.local/bin"
 
 }
 
