feat(cli): update update_command on unix & windows

diff --git a/scripts/unix/dotfiles b/scripts/unix/dotfiles
--- a/scripts/unix/dotfiles
+++ b/scripts/unix/dotfiles
@@ -367,6 +367,8 @@ dotfiles_install_command() {
 }
 
 dotfiles_update_command() {
+  log_task "Updating dotfiles"
+
   if [[ -n "${args[--local]}" ]]; then
   	set -- apply
   else
@@ -377,30 +379,41 @@ dotfiles_update_command() {
   	set -- "$@" --refresh-externals="${args["--refresh-externals"]}"
   fi
 
-  command_exec chezmoi "$@"
+  chezmoi "$@" || error "Failed to update dotfiles"
   log_success "Updated dotfiles"
 
   if [[ -n "${args["--cli"]}" ]]; then
   	script_dir="$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/dotfiles"
+  	if [[ ! -f "${script_dir}" ]]; then
+  		error "Could not find '${script_dir}'"
+  	fi
 
   	updated_script_dir=$(realpath "$(chezmoi source-path)/../scripts/unix/dotfiles")
+  	if [[ ! -f "${updated_script_dir}" ]]; then
+  		error "Could not find '${updated_script_dir}'"
+  	fi
 
-  	log_task "Replacing CLI executable in '${script_dir}'"
-  	command_exec cp -f "${updated_script_dir}" "${script_dir}"
+  	if [[ "${script_dir}" == "${updated_script_dir}" ]]; then
+  		log_success "The CLI is already up to date"
+  		exit 0
+  	fi
+
+  	log_task "Updating CLI"
+  	cp -f "${updated_script_dir}" "${script_dir}" || error "Failed to sync 'dotfiles'"
   	log_success "Updated the CLI to the latest version"
   fi
 
   if [[ -n "${args["--nvim"]}" ]]; then
   	log_task "Updating Neovim"
-  	command_exec bob update --all
+  	bob update --all || error "Failed to update Neovim"
   	log_success "Updated Neovim to the latest version"
 
   	log_task "Updating Neovim plugins"
-  	command_exec nvim --headless -c "lua vim.schedule(function() vim.api.nvim_create_autocmd('User', { pattern = 'LazySync', command = 'qa' }); require('lazy').sync({ show = false }) end)"
+  	nvim --headless -c "lua vim.schedule(function() vim.api.nvim_create_autocmd('User', { pattern = 'LazySync', command = 'qa' }); require('lazy').sync({ show = false }) end)" || error "Failed to update Neovim plugins"
   	log_success "Updated Neovim plugins"
 
   	log_task "Updating Mason packages"
-  	command_exec nvim --headless -c "lua vim.schedule(function() vim.api.nvim_create_autocmd('User', { pattern = 'MasonToolsUpdateCompleted', command = 'qa' }); require('mason-tool-installer').check_install(true) end)"
+  	nvim --headless -c "lua vim.schedule(function() vim.api.nvim_create_autocmd('User', { pattern = 'MasonToolsUpdateCompleted', command = 'qa' }); require('mason-tool-installer').check_install(true) end)" || error "Failed to update Mason packages"
   	log_success "Updated Mason packages"
 
   	log_task "Syncing 'lazy.lock.json' file"
@@ -414,19 +427,20 @@ dotfiles_update_command() {
   	if [[ ! -f "${updated_lazy_lock_path}" ]]; then
   		error "Could not find 'lazy-lock.json' file in '${config_path}'"
   	fi
-  	command_exec cp -f "${updated_lazy_lock_path}" "${lazy_lock_path}"
+  	cp -f "${updated_lazy_lock_path}" "${lazy_lock_path}" || error "Failed to sync 'lazy-lock.json' file"
   	log_success "Synced 'lazy-lock.json' file"
 
+  	log_task "Committing 'lazy-lock.json' file"
   	if git diff --quiet --exit-code -- "${lazy_lock_path}"; then
   		log_info "No changes in 'lazy-lock.json' file. Skip committing."
   		exit 0
   	fi
   	current_path=$(pwd)
-  	cd "$(realpath "$(chezmoi source-path)/..")" || error "Could not cd to '$(chezmoi source-path)/..'"
-  	command_exec git add "${lazy_lock_path}" || error "Could not add 'lazy-lock.json' file"
-  	command_exec git commit "${lazy_lock_path}" -m "chore(nvim): update lazy-lock.json" || error "Could not commit 'lazy-lock.json' file"
-  	cd "${current_path}" || error "Could not cd back to current working directory"
+  	cd "$(realpath "$(chezmoi source-path)/..")" || error "Failed to set current path to '$(chezmoi source-path)/..'"
+  	git add "${lazy_lock_path}" || error "Failed to add 'lazy-lock.json' file to git"
+  	git commit "${lazy_lock_path}" -m "chore(nvim): update lazy-lock.json" || error "Failed to commit 'lazy-lock.json' file"
   	log_success "Committed 'lazy-lock.json' file"
+  	cd "${current_path}" || error "Failed to set current path to '${current_path}'"
   fi
 
 }
