feat(cli): add Bash completions

diff --git a/scripts/unix/dotfiles b/scripts/unix/dotfiles
--- a/scripts/unix/dotfiles
+++ b/scripts/unix/dotfiles
@@ -29,10 +29,11 @@ dotfiles_usage() {
   echo
 
   printf "%s\n" "Commands:"
-  printf "  %s   Download dotfiles from the internet\n" "download"
-  printf "  %s   Install dotfiles with chezmoi\n" "install "
-  printf "  %s   Update dotfiles with chezmoi\n" "update  "
-  printf "  %s   Edit dotfiles\n" "edit    "
+  printf "  %s   Shell to generate completion\n" "completion"
+  printf "  %s   Download dotfiles from the internet\n" "download  "
+  printf "  %s   Install dotfiles with chezmoi\n" "install   "
+  printf "  %s   Update dotfiles with chezmoi\n" "update    "
+  printf "  %s   Edit dotfiles\n" "edit      "
   echo
 
   if [[ -n $long_usage ]]; then
@@ -43,6 +44,32 @@ dotfiles_usage() {
     echo
     printf "  %s\n" "--version, -v"
     printf "    Show version number\n"
+    echo
+
+  fi
+}
+
+dotfiles_completion_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "dotfiles completion - Shell to generate completion\n"
+    echo
+
+  else
+    printf "dotfiles completion - Shell to generate completion\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  dotfiles completion\n"
+  printf "  dotfiles completion --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -300,6 +327,80 @@ error() {
 	exit 1
 }
 
+send_completions() {
+  echo $'# dotfiles completion                                      -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_dotfiles_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $'  '
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_dotfiles_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    \'update\'*\'--refresh-externals\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_dotfiles_completions_filter "always auto never")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'edit\'*\'--hardlink\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_dotfiles_completions_filter "true false")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'completion\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_dotfiles_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'update\'*\'-R\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_dotfiles_completions_filter "always auto never")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'download\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_dotfiles_completions_filter "--branch --help --repo --ssh -b -h -r")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'install\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_dotfiles_completions_filter "--help --one-shot -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'update\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_dotfiles_completions_filter "--cli --help --local --nvim --refresh-externals -R -h -l")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'edit\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_dotfiles_completions_filter "--apply --hardlink --help --neovide --watch -a -h -n -w")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_dotfiles_completions_filter "--help --version -h -v completion download edit install update")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'complete -F _dotfiles_completions dotfiles'
+  echo $''
+  echo $'# ex: filetype=sh'
+}
+
 validate_dir_exists() {
   [[ -d "$1" ]] || echo "must be an existing directory"
 }
@@ -314,6 +415,11 @@ validate_integer() {
 
 validate_not_empty() {
   [[ -z "$1" ]] && echo "must not be empty"
+}
+
+dotfiles_completion_command() {
+  send_completions()
+
 }
 
 dotfiles_download_command() {
@@ -524,6 +630,13 @@ parse_requirements() {
   case $action in
     -*) ;;
 
+    completion)
+      action="completion"
+      shift
+      dotfiles_completion_parse_requirements "$@"
+      shift $#
+      ;;
+
     download)
       action="download"
       shift
@@ -563,6 +676,46 @@ parse_requirements() {
       ;;
 
   esac
+
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+dotfiles_completion_parse_requirements() {
+
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        dotfiles_completion_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  action="completion"
 
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -914,6 +1067,7 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "completion") dotfiles_completion_command ;;
     "download") dotfiles_download_command ;;
     "install") dotfiles_install_command ;;
     "update") dotfiles_update_command ;;
