chore(cli): update bashly

diff --git a/scripts/unix/dotfiles b/scripts/unix/dotfiles
--- a/scripts/unix/dotfiles
+++ b/scripts/unix/dotfiles
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.6 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.9 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
@@ -611,7 +611,6 @@ dotfiles_download_parse_requirements() {
       --repo | -r)
 
         if [[ -n ${2+x} ]]; then
-
           args['--repo']="$2"
           shift
           shift
@@ -624,7 +623,6 @@ dotfiles_download_parse_requirements() {
       --branch | -b)
 
         if [[ -n ${2+x} ]]; then
-
           args['--branch']="$2"
           shift
           shift
@@ -648,7 +646,6 @@ dotfiles_download_parse_requirements() {
       *)
 
         if [[ -z ${args['target']+x} ]]; then
-
           args['target']=$1
           shift
         else
@@ -704,7 +701,6 @@ dotfiles_install_parse_requirements() {
       *)
 
         if [[ -z ${args['sourceDir']+x} ]]; then
-
           args['sourceDir']=$1
           shift
         else
@@ -763,7 +759,6 @@ dotfiles_update_parse_requirements() {
       --refresh-externals | -R)
 
         if [[ -n ${2+x} ]]; then
-
           args['--refresh-externals']="$2"
           shift
           shift
@@ -853,7 +848,6 @@ dotfiles_edit_parse_requirements() {
       --hardlink)
 
         if [[ -n ${2+x} ]]; then
-
           args['--hardlink']="$2"
           shift
           shift
@@ -877,12 +871,6 @@ dotfiles_edit_parse_requirements() {
       *)
 
         if [[ -z ${args['target']+x} ]]; then
-
-          if [[ -n $(validate_file_exists "$1") ]]; then
-            printf "validation error in %s:\n%s\n" "TARGET" "$(validate_file_exists "$1")" >&2
-            exit 1
-          fi
-
           args['target']=$1
           shift
         else
@@ -896,6 +884,11 @@ dotfiles_edit_parse_requirements() {
   done
 
   [[ -n ${args['target']:-} ]] || args['target']=""
+
+  if [[ -v args['target'] && -n $(validate_file_exists "${args['target']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "TARGET" "$(validate_file_exists "${args['target']:-}")" >&2
+    exit 1
+  fi
 
   if [[ ${args['--hardlink']:-} ]] && [[ ! ${args['--hardlink']:-} =~ ^(true|false)$ ]]; then
     printf "%s\n" "--hardlink must be one of: true, false" >&2
