feat(arch): get a working version of ddcutil

diff --git a/home/.chezmoiscripts/arch/run_after_04-configure-brightness.sh.tmpl b/home/.chezmoiscripts/arch/run_after_04-configure-brightness.sh.tmpl
--- a/home/.chezmoiscripts/arch/run_after_04-configure-brightness.sh.tmpl
+++ b/home/.chezmoiscripts/arch/run_after_04-configure-brightness.sh.tmpl
@@ -19,28 +19,28 @@ else
 	exit 1
 fi
 
-_log -l info "Checking if ddcci module is loaded"
+# _log -l info "Checking if ddcci module is loaded"
 
-# Check if the ddcci kernel module is loaded
-if lsmod | grep -q '^ddcci'; then
-	_log -l warn "ddcci module is already loaded"
-else
-	# Load the ddcci kernel module
-	_spin "Loading ddcci module" -- sudo modprobe ddcci
-	_log -l info "Loaded ddcci module"
-fi
+# # Check if the ddcci kernel module is loaded
+# if lsmod | grep -q '^ddcci'; then
+# 	_log -l warn "ddcci module is already loaded"
+# else
+# 	# Load the ddcci kernel module
+# 	_spin "Loading ddcci module" -- sudo modprobe ddcci
+# 	_log -l info "Loaded ddcci module"
+# fi
 
-# Extract the device number using ddcutil
-device_number=$(ddcutil detect | grep -oE 'i2c-[0-9]+')
+# # Extract the device number using ddcutil
+# device_number=$(ddcutil detect | grep -oE 'i2c-[0-9]+')
 
-# Check if device number is found
-if [[ -n "${device_number}" ]]; then
-	# Attempt to create the new device entry
-	if ! echo "ddcci 0x37" | sudo tee "/sys/bus/i2c/devices/${device_number}/new_device" >/dev/null 2>&1; then
-		_log -l warn "Device entry for external display already exists"
-		exit
-	fi
-else
-	_log -l error "Failed to find ddcci device number for external display"
-	exit 1
-fi
+# # Check if device number is found
+# if [[ -n "${device_number}" ]]; then
+# 	# Attempt to create the new device entry
+# 	if ! echo "ddcci 0x37" | sudo tee "/sys/bus/i2c/devices/${device_number}/new_device" >/dev/null 2>&1; then
+# 		_log -l warn "Device entry for external display already exists"
+# 		exit
+# 	fi
+# else
+# 	_log -l error "Failed to find ddcci device number for external display"
+# 	exit 1
+# fi
