feat(scripts): use `gum` and remove legacy logs and spinners

diff --git a/home/.chezmoiscripts/arch/run_after_06-configure-brightness.sh.tmpl b/home/.chezmoiscripts/arch/run_after_06-configure-brightness.sh.tmpl
--- a/home/.chezmoiscripts/arch/run_after_06-configure-brightness.sh.tmpl
+++ b/home/.chezmoiscripts/arch/run_after_06-configure-brightness.sh.tmpl
@@ -5,34 +5,42 @@
 # The following line is for ShellCheck to correctly identify the above included library
 true || source "../../.chezmoitemplates/bash-library.sh"
 
-configure_brightness() {
-	# Check if i2c_dev is loaded
-	if ! ls /dev/i2c-* >&/dev/null; then
-		echo "i2c_dev" | sudo tee "/etc/modules-load.d/i2c.conf"
-		echo "Arch Linux: A reboot is required to load i2c_dev"
-		exit 1
+_log -l info "Checking if i2c_dev module is loaded"
+
+sudo -v
+
+# Check if i2c_dev is loaded
+if ls /dev/i2c-* >&/dev/null; then
+	_log -l warn "i2c_dev module is already loaded"
+else
+	_spin "Adding i2c_dev to /etc/modules-load.d/" -- echo "i2c_dev" | sudo tee "/etc/modules-load.d/i2c.conf"
+	_log -l info "Loaded i2c_dev module"
+	_log -l fatal "A reboot is required"
+	exit 1
+fi
+
+_log -l info "Checking if ddcci module is loaded"
+
+# Check if the ddcci kernel module is loaded
+if lsmod | grep -q '^ddcci'; then
+	_log -l warn "ddcci module is already loaded"
+else
+	# Load the ddcci kernel module
+	_spin "Loading ddcci module" -- sudo modprobe ddcci
+	_log -l info "Loaded ddcci module"
+fi
+
+# Extract the device number using ddcutil
+device_number=$(ddcutil detect | grep -oE 'i2c-[0-9]+')
+
+# Check if device number is found
+if [[ -n "${device_number}" ]]; then
+	# Attempt to create the new device entry
+	if ! echo "ddcci 0x37" | sudo tee "/sys/bus/i2c/devices/${device_number}/new_device" >/dev/null 2>&1; then
+		_log -l warn "Device entry for external display already exists"
+		exit
 	fi
-
-	# Extract the device number using ddcutil
-	device_number=$(ddcutil detect | grep -oE 'i2c-[0-9]+')
-
-	# Check if the ddcci kernel module is loaded
-	if ! lsmod | grep -q '^ddcci'; then
-		# Load the ddcci kernel module
-		sudo modprobe ddcci
-	fi
-
-	# Check if device number is found
-	if [[ -n "${device_number}" ]]; then
-		# Attempt to create the new device entry
-		if ! echo "ddcci 0x37" | sudo tee "/sys/bus/i2c/devices/${device_number}/new_device" >/dev/null 2>&1; then
-			echo "Arch Linux: Device entry already exists"
-			exit 2
-		fi
-	else
-		echo "Arch Linux: Failed to find ddcci device number"
-		exit 1
-	fi
-}
-
-show_spinner "configure_brightness" "Arch Linux: Checking if brightness controls are configured" "Arch Linux: Configured brightness controls"
+else
+	_log -l error "Failed to find ddcci device number for external display"
+	exit 1
+fi
