feat(cli): add Neovim options for update command

diff --git a/scripts/dotfiles b/scripts/dotfiles
--- a/scripts/dotfiles
+++ b/scripts/dotfiles
@@ -174,6 +174,10 @@ dotfiles_update_usage() {
     printf "    Update the CLI itself. This defaults to false.\n"
     echo
 
+    printf "  %s\n" "--nvim"
+    printf "    Update Neovim plugins, Mason packages and sync lazy-lock.json file if it\n    exists.\n"
+    echo
+
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
@@ -425,7 +429,6 @@ dotfiles_update_command() {
   fi
 
   command_exec chezmoi "$@"
-
   log_success "Updated dotfiles"
 
   if [[ -n "${args["--cli"]}" ]]; then
@@ -433,9 +436,56 @@ dotfiles_update_command() {
 
   	updated_script_dir=$(realpath "$(eval echo "$(chezmoi source-path)")/../scripts/dotfiles")
 
+  	log_task "Replacing CLI executable in '${script_dir}'"
   	command_exec cp -f "${updated_script_dir}" "${script_dir}"
-
   	log_success "Updated the CLI to the latest version"
+  fi
+
+  if [[ -n "${args["--nvim"]}" ]]; then
+  	if ! command -v bob >/dev/null; then
+  		error "To update Neovim, you must have bob."
+  	fi
+  	log_task "Updating Neovim"
+  	command_exec bob update --all
+  	log_success "Updated Neovim"
+
+  	if ! command -v nvim >/dev/null; then
+  		error "To update Neovim plugins and Mason packages, you must have Neovim."
+  	fi
+
+  	log_task "Updating Neovim plugins"
+  	command_exec nvim --headless -c "lua vim.schedule(function() require('lazy').sync(); vim.cmd('qa!') end)"
+  	log_success "Updated Neovim plugins"
+
+  	log_task "Updating Mason packages"
+  	command_exec nvim --headless -c "lua vim.schedule(function() require('mason-tool-installer').check_install(true); vim.cmd('qa!') end)"
+  	log_success "Updated Mason packages"
+
+  	if ! command -v chezmoi >/dev/null; then
+  		error "To sync the 'lazy.lock.json' file, you must have chezmoi."
+  	fi
+
+  	log_task "Syncing 'lazy.lock.json' file"
+  	source_path=$(chezmoi source-path)
+  	lazy_lock_path=$(find "${source_path}" -type f -name "*lazy-lock.json" -print -quit)
+  	if [[ ! -f "${lazy_lock_path}" ]]; then
+  		error "Could not find 'lazy-lock.json' file in '${source_path}'"
+  	fi
+  	config_path="${XDG_CONFIG_HOME:-${HOME}/.config}/nvim"
+  	updated_lazy_lock_path=$(find "${config_path}" -type f -name "*lazy-lock.json" -print -quit)
+  	if [[ ! -f "${updated_lazy_lock_path}" ]]; then
+  		error "Could not find 'lazy-lock.json' file in '${config_path}'"
+  	fi
+  	command_exec cp -f "${updated_lazy_lock_path}" "${lazy_lock_path}"
+  	log_success "Synced 'lazy-lock.json' file"
+
+  	if ! command -v git >/dev/null; then
+  		error "To sync the 'lazy.lock.json' file, you must have git."
+  	fi
+  	cd $(realpath "$(chezmoi source-path)/..") || error "Could not cd to dotfiles directory"
+  	command_exec git add "${lazy_lock_path}"
+  	command_exec git commit "${lazy_lock_path}" -m "chore(nvim): update lazy-lock.json"
+  	log_success "Commited 'lazy-lock.json' file"
   fi
 
 }
@@ -751,6 +801,12 @@ dotfiles_update_parse_requirements() {
       --cli)
 
         args['--cli']=1
+        shift
+        ;;
+
+      --nvim)
+
+        args['--nvim']=1
         shift
         ;;
 
