feat(cli): only commit if changes were detected

diff --git a/scripts/dotfiles b/scripts/dotfiles
--- a/scripts/dotfiles
+++ b/scripts/dotfiles
@@ -482,10 +482,16 @@ dotfiles_update_command() {
   	if ! command -v git >/dev/null; then
   		error "To sync the 'lazy.lock.json' file, you must have git."
   	fi
+  	if git diff --exit-code -- "${lazy_lock_path}"; then
+  		log_info "No changes in 'lazy-lock.json' file. Skip committing."
+  		exit 0
+  	fi
+  	current_path=$(pwd)
   	cd $(realpath "$(chezmoi source-path)/..") || error "Could not cd to dotfiles directory"
-  	command_exec git add "${lazy_lock_path}"
+  	command_exec git add "${lazy_lock_path}" || error "Could not add 'lazy-lock.json' file"
   	command_exec git commit "${lazy_lock_path}" -m "chore(nvim): update lazy-lock.json"
-  	log_success "Commited 'lazy-lock.json' file"
+  	cd "${current_path}" || error "Could not cd to current directory"
+  	log_success "Committed 'lazy-lock.json' file"
   fi
 
 }
